### ISSUE TITLE
addition of failed_tasks seem to negatively affect performance

### ISSUE THREAD

**Issue by hgromer** [ecrl/ecabc#26]
There has been a drop in accuracy since adding the feature which ensures bees try to find a new food source 'n' amount of times before searching for a new random location as per the wikipedia article.

https://en.wikipedia.org/wiki/Artificial_bee_colony_algorithm

**Comment by tjkessler** [comment]
It looks like you're incrementing the abandonment counter if the bee's fitness is worse than the average - the bee shouldn't reference the population's average fitness, it should reference its current food source. I.e., increment abandonment if the bee's mutated food source is worse than its current food source.
