### ISSUE TITLE
Need to pass additional arguments to fitness function

### ISSUE THREAD

**Issue by tjkessler** [ecrl/ecabc#28]
With current ECNet implementation of ecabc 1.X, the fitness function is defined in the tune_hyperparameters() method (see master branch). With the addition of multiprocessing to the ABC, the local definition of the fitness function cannot be multiprocessed:
```
AttributeError: Can't pickle local object 'Server.tune_hyperparameters.<locals>.test_neural_network'
```
Therefore, I've had to move the definition of the cost function outside the tune_hyperparameters() method.

This causes a few issues:
- The cost function does not have any Server attributes
    - Currently loaded data is not present, so it would have to be re-loaded
        - Without hard-coding the file path, there is no way to tell the fitness function which data to load
    - To create a neural network, lower level usage of ecnet/model.py is required
        - This is a minor issue, genetic algorithm implementation already does this

A way to pass arbitrary arguments to a cost function would be beneficial. I.e., when the ABC is initialized, an array/tuple/dictionary could be passed to it, which is then relayed to the cost function during optimization. ECNet could then pass its currently loaded data to the ABC.

**Comment by hgromer** [comment]
This is something I wanted to add soon. Thanks for the heads up.
