### ISSUE TITLE
(Ongoing) OnlookerBee's new positions are not limited by minimum or maximum values

### ISSUE THREAD

**Issue by tjkessler** [ecrl/ecabc#32]
The calculate_positions() method of the OnlookerBee class does not adhere to the minimum and maximum values specified during ABC initialization:
```python
    def calculate_positions(self, first_bee, second_bee, value_types):
        '''
        Calculate the positions when merging two bees
        '''
        new_values = first_bee.values
        index = randint(0, len(first_bee.values)-1)
        # Here
        value = first_bee.values[index] + abs(np.random.uniform(-1, 1) \
                * (first_bee.values[index] - second_bee.values[index]))
        if value_types[index] == 'int':
            value = int(value)
        new_values[index] = value
        return new_values
```
For example, I have experience a variable (dropout_rate) being set to **1.47** when my value argument is:
```python
('float', (0.0, 1.0))
```

**Comment by hgromer** [comment]
This has been *fixed* by added limits to the what the new value can be. This seems like a more fundamental issue that I'd like to look into more. We are using the formula found on Wikipedia to merge the two bees.
