### ISSUE TITLE
to_modify is an empty list

### ISSUE THREAD

**Issue by sanskriti-s** [ecrl/ecabc#34]
https://github.com/ECRL/ecabc/blob/dac7f90754741fc159198ac48918c10eb5141f07/ecabc/abc.py#L246

Based on the sample code, when you enter this section, the list appears to be empty

**Comment by hgromer** [comment]
Only for the first iteration. Not a huge deal, will update next patch.

**Comment by sanskriti-s** [comment]
Also why are you enumerating through it anyway. This is what the logic was on the algorithm-refactor branch:
```
            for i in range(foodNumber):  
                self.employedList[i].probability = self.employedList[i].fitness/totalFit
            #pick based on probability 
            for i in range(foodNumber):
                x = random.uniform(0,1)
                totalProbability = 0.0
                for item, item_probability in zip (employedList,employedList.probability):
                    totalProbability += item_probability
                    if x < totalProbability: 
                        chosenEmployerBee= item
                        break
                onlookerList[i] = chosenEmployerBee    
```

in which food number is the total number of employer bees

**Comment by hgromer** [comment]
They are bees that have the be modified. Their limit has not yet been reached, they are entered into the list of bees that may be picked to be merged depending on their probability. Bees not in to_modified have been reset, and can be merged the next time around.

**Comment by tjkessler** [comment]
Is this still an issue with the current version?
