### ISSUE TITLE
Multiprocessing error

### ISSUE THREAD

**Issue by sanskriti-s** [ecrl/ecabc#38]
If you call apply_async but then call get in a for loop just after, it will block the program until each function completes anyway, so doesn't this defeat the purpose of using the multiprocessing?https://github.com/ECRL/ecabc/blob/2.2.0/ecabc/abc.py#L232

**Comment by hgromer** [comment]
No because the computations happen on a separate process. If it were non blocking the program would proceed without the calculations having completed.

**Comment by sanskriti-s** [comment]
Right, okay.
